### ISSUE TITLE
Get a list of variables to be set

### ISSUE THREAD

**Issue by darren-y** [fasseg/exp4j#66] opened 2016-07-27 16:32 UTC
I'd like for the ability to get a list of variables as parsed from exp4j to do pre-validation of the variable names.  This looks like it would be as simple as exposing a read only set or list of the Expression's variable list.

**Comment by risenhoover** [comment] 2016-10-05 23:25
+1

**Comment by risenhoover** [comment] 2016-10-06 03:59
I just submitted a pull request that implements this.

**Comment by risenhoover** [comment] 2016-10-13 16:48
This issue should be resolved with this pull request https://github.com/fasseg/exp4j/pull/68

**Comment by risenhoover** [comment] 2016-10-15 19:35
So it looks like my pull request doesn't actually solve the problem. The issue is that I've put getVariableNames() in the Expression, which is returned from ExpressionBuilder, but only *after* the .build() method is called. The .build() method requires the variables to be set or it throws an exception.

We need to be able to create an ExpressionBuilder (without calling build()), and then query the ExpressionBuilder to get the variable names, set them, and then finish by calling build().

**Comment by fasseg** [comment] 2016-12-09 12:27
Hey Guys, 
I do have January off and will invest some time to get exp4j up to date. Unfortunately I do not have enough time to do this properly earlier...

**Comment by risenhoover** [comment] 2017-01-15 23:48
@fasseg When will you push this pull request to maven so I can use it in production builds?

**Comment by fasseg** [comment] 2017-01-18 12:53
@risenhoover I will roll a new release in January, so stay tuned over the next couple of days :)

**Comment by fasseg** [comment] 2017-01-30 14:05
released in 0.4.8

**Closed by fasseg** 2017-01-30 14:05 UTC
