### ISSUE TITLE
Numberparsing doesn't honor locale

### ISSUE THREAD

**Issue by onyxbits** [fasseg/exp4j#30] opened 2015-01-26 17:18 UTC
Hi,
I'm using exp4j in TradeTrax (https://github.com/onyxbits/TradeTrax) and would like to integrate it deeper (allowing for calculations to be done wherever numbers can be entered). The thing that keeps me from this is that TradeTrax automatically adapts to the user's locale for formating numbers, but exp4j doesn't, it always uses the "." character for fractions (in germany, we use "," for that purpose). The culprit seems to be Tokenizer.java, line 60, where the dot is hardcoded. Would it be possible to make this a variable which is passed in through the constructor and can be set from the ExpressionBuilder?

The locale specific decimalseperator can be found via java.text.DecimalFormatSymbols.getDecimalSeperator.

**Comment by fasseg** [comment] 2015-01-27 07:49
Hola @onyxbits 
This issue has been raised a couple of times. The problem is that you cannot differentiate in between two arguments and a number using a comma as a decimal separator:
E.g. is log(3,2) meant to be the natural logarithm of 3.2, or is it the logarithm of 3 to the base 2?
see https://github.com/fasseg/exp4j/issues/24

**Comment by fasseg** [comment] 2015-01-27 07:58
reopening since I didn't want to close it in the first place

**Comment by onyxbits** [comment] 2015-01-27 17:57
Ah, sorry for not checking the issue queue more thoroughly. 

I was afraid that there would be a little tripmine like that lying around somewhere.
Translating numbers first wouldn't work. If I called mult(x,y) as mult(2,5,5) it wouldn't be clear if I meant 2,5*5 or 2*5,5. So changing the argument seperator would be the only way to go, but honestly, I find everything except the "," to be inappropriate there.

Personally, I don't need functions, so I could probably go with forking. Is Tokenizer:60 the only line I would need to modify?

**Comment by leogtzr** [comment] 2015-01-27 18:28
I think @fasseg meant:
```java
// Russia
        DecimalFormat formatter = (DecimalFormat)DecimalFormat.getInstance(Locale.forLanguageTag("RU"));
        
        try {
            Expression e = new ExpressionBuilder("3 * x")
                .variables("x")
                .build()
                .setVariable("x", formatter.parse("223,0").doubleValue());
            double result = e.evaluate();
            System.out.println(result);
        } catch(NumberFormatException ex) {
            System.out.println(ex);
        } catch(ParseException ex) {
            System.out.println(ex);
        }
```

**Comment by fasseg** [comment] 2015-02-16 15:07
@onyxbits 
Did @leogtzr example help? Can you correclty evaluate your expression now?

**Comment by onyxbits** [comment] 2015-02-17 00:58
@fasseg 
I'm afraid @leogtzr example misses the point. My expression comes directly from the user. I literally have to evaluate a string like "10+10*0,1". I could do something like:

       "10+10*0,1".replace(',','.');

But I'm not really happy about this. Especially not as this would obviously crash and burn when functions are involved.

I think, we can close the issue as "Won't fix". I see no way in which you could have functions with an argument list and locale specific number formatting.

**Comment by fasseg** [comment] 2015-02-23 07:16
I can't think of a better solution than preprocessing the input, or letting the user change the argument separator as well. But if somone can think of something feel free to reopen the issue ;)

**Closed by fasseg** 2015-02-23 07:16 UTC
