### ISSUE TITLE
Variable names and multiplication

### ISSUE THREAD

**Issue by michbudz** [fasseg/exp4j#37] opened 2015-04-21 14:18 UTC
Hi!
I have some trouble with variable name ending with number.
Suppose I have variable name 'var1' and expression with this variable like 'var123 + 100'.
In my opinion, ExpressionBuilder should return exception with error 'No variable name var123'.
But this is not happening. ExpressionBuilder evaluate this expression like 'var1 * 23 + 100'. 
This incident may cause a lot of mistakes, especially when we have a lot of variables ending with number.
Is there any chance to disable multiplication with no sign '*'? Do you have any other ideas?

**Comment by fasseg** [comment] 2015-04-22 05:42
That's a good point.
I think it would indeed be possible, to have something like this:

```Java
Expression e = new ExpressionBuilder("x_12")
        .variables("x_1")
        .implicitMultiplication(false)
        .build()
        .setVariable("x_1", 2)
double result = e.evaluate();
```
by letting users turn off implicit multiplication using a builder method we should be safe to not introduce regressions in existing software

**Comment by michbudz** [comment] 2015-04-22 08:32
Is it possible to add this solution to source code in the nearest future?

**Comment by fasseg** [comment] 2015-04-22 10:11
@michbudz I added a feature branch which has the before mentioned capabilities. 
You can check it out here:
https://github.com/fasseg/exp4j/tree/implicitmultiplication-optional

I will not merge this in master yet, since I'd like some feedback from @leogtzr and @dktcoding if they see any problems with this approach.

**Comment by michbudz** [comment] 2015-04-22 10:24
Thanks a lot!

**Comment by leogtzr** [comment] 2015-04-23 05:44
@fasseg
Is this feature only for variables followed by numbers? I just tested this:

```java
Expression e = new ExpressionBuilder("x_1sin(2.0)")
        .variable("x_1")
        .implicitMultiplication(false)
        .build()
        .setVariable("x_1", 2);
        result = e.evaluate(); // 1.8185948536513634
```
it's returning a valid numeric value even with the implicitMultiplication flag on false.

**Comment by fasseg** [comment] 2015-04-23 06:06
@leogtzr ah it's good to work with professionals. I indeed forgot to add it for brackets and indeed variables. I will push an update soon.

**Comment by fasseg** [comment] 2015-04-23 14:01
I added checks for variables/functions/paratheses.
So this should work as intended now

**Comment by fasseg** [comment] 2015-06-23 13:44
closing this since it seems fixed

**Closed by fasseg** 2015-06-23 13:44 UTC
